$(document).ready(function(){
    $('img').click(function(){
        $(this).hide('slow')
    })
    $('button').click(function(){
        $('img').each(function(){
            $(this).show()
        })
    })
})